### ISSUE TITLE
Add support for ledger wallets

### ISSUE THREAD

**Issue by denalimarsh** [Kava-Labs/javascript-sdk#4]
What do you think about adding ledger support? Not within the scope of this PR, but making an issue for it and adding in the future.

_Originally posted by @denalimarsh in https://github.com/Kava-Labs/javascript-sdk/pull/1_

**Comment by thomasmost** [comment]
@denalimarsh was this resolved by the PR #1 ?

**Comment by thomasmost** [comment]
Closing as stale
