### ISSUE TITLE
Lodash removal

### ISSUE THREAD

**Issue by Distortedlogic** [Kava-Labs/javascript-sdk#63]
Lodash is notorious for increasing bundle sizes. I only saw the functions "get" and "sortby" in 4 files, both of which can be easily implemented with one liners in JS without lodash. So lodash is not adding any value for the large bundle size cost.

![image](https://user-images.githubusercontent.com/54854447/118655203-4d607f80-b7b7-11eb-8289-eee65ae87810.png)

**Comment by denalimarsh** [comment]
Agreed, should be an easy fix. I'll create a ticket for this.
